[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "/events"
  to = "/Events-Location/Sydney/"
[[redirects]]
  from = "/Events-Location/Sydney/*"
  to = "http://ravereviewz-286156834.ap-southeast-2.elb.amazonaws.com/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/Event/*"
  to = "http://ravereviewz-286156834.ap-southeast-2.elb.amazonaws.com/:splat"
  status = 200
  force = true
